### ISSUE TITLE
Update the MVC sample to include an authorization policy using the scopes contained in the token

### ISSUE THREAD

**Issue by kevinchalet** [aspnet-contrib/AspNet.Security.OpenIdConnect.Samples#6]
/cc @DovydasNavickas

**Comment by kevinchalet** [comment]
@DovydasNavickas is this something you'd like to extend to the SignalR sample?
I guess it's less trivial than adding a simple `AuthorizeAttribute` when using raw connections :smile:

**Comment by DovydasNavickas** [comment]
I guess with SignalR 2.0 and authentication there's nothing as trivial as adding `AuthorizeAttribute`, doesn't matter if you use PersistentConnections (raw) or Hubs :smile: (I'm looking at you @davidfowl for SignalR 3.0. I could give some good feedback, when you start working on it, just ping me)

Either way, authorization policy is contained in IdentityServer, if I understand correctly, which makes it universal rather than SignalR problem, doesn't it?

**Comment by kevinchalet** [comment]
> Either way, authorization policy is contained in IdentityServer, if I understand correctly, which makes it universal rather than SignalR problem, doesn't it?

Well, this ticket was more about the authorization policy of the resource server (that may reject tokens missing a specific scope for instance), but actually, the 2 things are linked.

Done: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Samples/commit/5ef927857f1ebb67bc741f1e0c77aea041141237 :clap:
